front/urls.py
from django.urls import path
from . import views


app_name = 'front'
urlpatterns = [
    path('', views.index, name='index')
]

search/urls.py
# encoding: utf-8

from django.urls import path
from .views import BasicSearchView, FacetedSearchView

app_name = 'search'
urlpatterns = [
    path('faceted', FacetedSearchView.as_view(), name='faceted'),
    path('', BasicSearchView.as_view(), name='basic'),
]

shoppingmall/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
# Admin settings written by Mohammad Ashrafuddin Ferdousi
from . import admin_settings

admin_settings.configurations()

urlpatterns = [
    path('search/', include('search.urls')),
    path('products/', include('products.urls')),
    path('shops/', include('shops.urls')),
    path('malls/', include('malls.urls')),
    path('pages/', include('pages.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('front.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/models.py
from django.db import models

# Create your models here.

search/forms.py
from django import forms
from haystack.forms import SearchForm as HaystackBasicSearchForm, FacetedSearchForm as HaystackFacetedSearchForm


class BasicSearchForm(HaystackBasicSearchForm):
    pass


class FacetedSearchForm(HaystackFacetedSearchForm):
    q = None

    searchable_price = forms.CharField(required=False, label=None, widget=forms.TextInput(attrs={
        'class': 'price-range-slider '
                 'hide-text-field',
        'type': 'text',
        'data-type': 'double',
        'data-min': '0',
        'data-max': '1000000',
        'data-from': '0',
        'data-to': '1000000',
        'data-grid': 'true'
    }))

    in_stock = forms.BooleanField(required=False, label='In Stock?', widget=forms.CheckboxInput({'checked': True}))

    def __init__(self, *args, **kwargs):
        super(FacetedSearchForm, self).__init__(*args, **kwargs)

    def search(self):
        searchable_price = self.cleaned_data['searchable_price']
        in_stock = self.cleaned_data['in_stock']

        sqs = self.searchqueryset

        if not self.is_valid():
            return self.no_query_found()

        if searchable_price:
            price_range_start, price_range_end = searchable_price.split(";")

            if price_range_start:
                sqs = sqs.filter(searchable_price__gte=price_range_start)

            if price_range_end:
                sqs = sqs.filter(searchable_price__lte=price_range_end)

        sqs = sqs.filter(in_stock=in_stock)

        return sqs

search/views.py
from haystack.generic_views import SearchView as HaystackSearchView, FacetedSearchView as HaystackFacetedSearchView
from .forms import FacetedSearchForm


class BasicSearchView(HaystackSearchView):
    form_name = 'basic_search_form'
    template_name = 'basic/search.html'


class FacetedSearchView(HaystackFacetedSearchView):
    form_class = FacetedSearchForm
    facet_fields = ['searchable_price', 'in_stock']
    form_name = 'faceted_search_form'
    template_name = 'faceted/search.html'

search/templates/shared/faceted/pagination.html
<div class="row">
    <div class="col-12">
        <div class="product-topbar d-xl-flex align-items-end justify-content-between">
            {% if page_obj.has_previous or page_obj.has_next %}
                <!-- Total Products -->
                <div class="total-products">
                    <p>Showing {{ page_obj.start_index }}-{{ page_obj.end_index }} of {{ page_obj.paginator.count}}</p>
                </div>
                <div class="row">
                    <div class="col-12">
                        <!-- Pagination -->
                        <nav aria-label="navigation">
                            <ul class="pagination justify-content-end">

                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?searchable_price={{ request.GET.searchable_price|urlencode }}{% if request.GET.in_stock %}&amp;in_stock={{ request.GET.in_stock }}{% endif %}&amp;page=1" aria-label="First">
                                        <span aria-hidden="true">&laquo;&laquo; </span>
                                        <span class="sr-only">First</span>
                                    </a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="?searchable_price={{ request.GET.searchable_price|urlencode }}{% if request.GET.in_stock %}&amp;in_stock={{ request.GET.in_stock }}{% endif %}&amp;page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                </li>
                            {% endif %}
                            {% for page_num in page_obj.paginator.page_range %}
                                {% if page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
                                    <li class="page-item {% if page_num == page_obj.number %} {{ "active" }} {% endif %}"><a class="page-link" href="?searchable_price={{ request.GET.searchable_price|urlencode}}{% if request.GET.in_stock %}&amp;in_stock={{ request.GET.in_stock }}{% endif %}&amp;page={{ page_num }}"> {{ page_num }}.</a></li>
                                {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?searchable_price={{ request.GET.searchable_price|urlencode }}{% if request.GET.in_stock %}&amp;in_stock={{ request.GET.in_stock }}{% endif %}&amp;page={{ page_obj.next_page_number }}" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="?searchable_price={{ request.GET.searchable_price|urlencode }}{% if request.GET.in_stock %}&amp;in_stock={{ request.GET.in_stock }}{% endif %}&amp;page={{page_obj.paginator.num_pages}}" aria-label="Last">
                                        <span aria-hidden="true">&raquo;&raquo;</span>
                                        <span class="sr-only">Last</span>
                                    </a>
                                </li>
                            {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>

search/templates/shared/faceted/search.html
{% load i18n static %}
<!-- ##### Single Widget ##### -->
<div class="widget price mb-auto">
    <!-- Widget Title -->
    <h6 class="widget-title">Price</h6>
    <div class="widget-desc">
        <form method="get" action="{% url 'search:faceted' %}">
            {{ faceted_search_form.searchable_price }}
            {{ faceted_search_form.in_stock }} {{ faceted_search_form.in_stock.label }}
            <input type="submit" value="Search" class="btn btn-primary align-right">
        </form>
    </div>
</div>